export { default as Calendar } from './Calendar'
export { default as NavBar } from './NavBar'
export { default as AddEvent} from './AddEvent'
export { default as Home } from './Home'
export { default as SingleDay} from './SingleDay'
export { default as ViewEventsModal } from './ViewEventsModal'
export { default as ModalUpdate } from './ModalUpdateEvent'
export { default as ModalAdd } from './ModalAddEvent' 