export { default as Calendar } from './Calendar'
export { default as NavBar } from './NavBar'
export { default as AddEvent} from './AddEvent'
export { default as Home } from './Home'
export { defauly as ViewEvents } from './ViewEvents'